# name: syncToGitee
# on:
#   push:
#     branches:
#       - gh-pages
# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Mirror the Github organization repos to Gitee.
#         uses: Yikun/hub-mirror-action@master
#         with:
#           src: 'github/username'
#           dst: 'gitee/username'
#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token:  ${{ secrets.GITEE_TOKEN }}
#           static_list: "learn-typescript"
